name: Build and Release Assets

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Create build archive
        run: |
          cd public
          zip -r ../build-assets-${{ github.sha }}.zip build/
          cd ..
          echo "Created build-assets-${{ github.sha }}.zip"
          ls -lh build-assets-${{ github.sha }}.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: Build Assets ${{ github.sha }}
          body: |
            Automated build assets for commit ${{ github.sha }}
            
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
          files: build-assets-${{ github.sha }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
